using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CozmoAPI.Enums
{
    public enum CozEventType : byte
    {
        UiDeviceConnected	= 0x0 	,
        AudioCallback	= 0x1	,
        AdvertisementRegistrationMsg	= 0x2	,
        AdvertisementMsg	= 0x3	,
        Ping	= 0x4	,
        DenyGameStart	= 0x5	,
        ObjectDiscovered	= 0x6	,
        ObjectConnectionState	= 0x7	,
        ObjectConnectionStateToRobot	= 0x8	,
        ObjectMoved	= 0x9	,
        ObjectStoppedMoving	= 0xa	,
        ObjectUpAxisChanged	= 0xb	,
        ObjectTapped	= 0xc	,
        ObjectPowerLevel	= 0xd	,
        FactoryTestResultEntry	= 0xe	,
        ImageChunk	= 0xf	,
        ImageImuData	= 0x10	,
        CameraCalibration	= 0x11	,
        IMURequest	= 0x12	,
        LoadedKnownFace	= 0x13	,
        RobotRenamedEnrolledFace	= 0x14	,
        MotorCalibration	= 0x15	,
        MotorAutoEnabled	= 0x16	,
        CliffEvent	= 0x17	,
        PotentialCliff	= 0x18	,
        ProxObstacle	= 0x19	,
        CarryStateUpdate	= 0x1a	,
        SetBodyRadioMode	= 0x1b	,
        AnimationState	= 0x1c	,
        UiDeviceAvailable	= 0x1d	,
        RobotConnectionResponse	= 0x1e	,
        RobotDisconnected	= 0x1f	,
        EngineRobotCLADVersionMismatch = 0x20	,
        ObjectAvailable	= 0x21	,
        ObjectUnavailable	= 0x22	,
        FeatureToggles	= 0x23	,
        GoingToSleep	= 0x24	,
        EngineLoadingDataStatus	= 0x25	,
        RobotState	= 0x26	,
        RobotDelocalized	= 0x27	,
        RobotPoked	= 0x28	,
        RobotStopped	= 0x29	,
        RobotOffTreadsStateChanged	= 0x2a	,
        RobotCliffEventFinished	= 0x2b	,
        RobotOnChargerPlatformEvent	= 0x2c	,
        ChargerEvent	= 0x2d	,
        UnexpectedMovement	= 0x2e	,
        RestoreRobotStatus	= 0x2f	,
        RestoreRobotOptions	= 0x30	,
        DebugString	= 0x31	,
        DebugAnimationString	= 0x32	,
        RobotProcessedImage	= 0x33	,
        RobotObservedObject	= 0x34	,
        RobotObservedPossibleObject	= 0x35	,
        ObjectProjectsIntoFOV	= 0x36	,
        RobotObservedFace	= 0x37	,
        RobotChangedObservedFaceID	= 0x38	,
        RobotObservedPet	= 0x39	,
        RobotObservedMotion	= 0x3a	,
        RobotDeletedFace	= 0x3b	,
        RobotDeletedObject	= 0x3c	,
        RobotDeletedAllObjects	= 0x3d	,
        RobotDeletedAllCustomObjects	= 0x3e	,
        CreatedFixedCustomObject	= 0x3f	,
        DefinedCustomObject	= 0x40	,
        RobotMarkedObjectPoseUnknown	= 0x41	,
        AvailableObjects	= 0x42	,
        RobotReadToolCode	= 0x43	,
        RobotReachedEnrollmentCount	= 0x44	,
        RobotErasedEnrolledFace	= 0x45	,
        RobotErasedAllEnrolledFaces	= 0x46	,
        RobotCompletedFactoryDotTest	= 0x47	,
        RobotCompletedAction	= 0x48	,
        BlockPickedUp	= 0x49	,
        BlockPlaced	= 0x4a	,
        AnimationAvailable	= 0x4b	,
        AnimationGroupAvailable	= 0x4c	,
        AnimationAborted	= 0x4d	,
        AnimationEvent	= 0x4e	,
        MoodState	= 0x4f	,
        RequestSetUnlockResult	= 0x50	,
        UnlockStatus	= 0x51	,
        UnlockedDefaults	= 0x52	,
        InitDebugConsoleVarMessage	= 0x53	,
        JsonDasLogMessage	= 0x54	,
        JsonDasLogAllSentMessage	= 0x55	,
        VerifyDebugConsoleFuncMessage  = 0x56	,
        VerifyDebugConsoleVarMessage	= 0x57	,
        LatencyMessage	= 0x58	,
        DeviceDataMessage	= 0x59	,
        BlockTapFilterStatus	= 0x5a	,
        UpdateEngineState	= 0x5b	,
        EngineErrorCodeMessage	= 0x5c	,
        CubeLightsStateTransition	= 0x5d	,
        BlockPoolDataMessage	= 0x5e	,
        NVStorageOpResult	= 0x5f	,
        FirmwareUpdateProgress	= 0x60	,
        FirmwareUpdateComplete	= 0x61	,
        RequestGameStart	= 0x62	,
        RequestEnrollFace	= 0x63	,
        SparkEnded	= 0x64	,
        SdkConnectionStatus	= 0x65	,
        SdkStatus	= 0x66	,
        BehaviorTransition	= 0x67	,
        RespondEnabledBehaviorList	= 0x68	,
        ReactionaryBehaviorTransition  = 0x69	,
        BehaviorObjectiveAchieved	= 0x6a	,
        OnboardingState	= 0x6b	,
        SupportInfo	= 0x6c	,
        EndOfMessage	= 0x6d	

    }    
}
